import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Blogging boy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<header>
<p>Blogger boy, Hey dood! the blog is yours!</p>
<nav>
<Link href="/">Home</Link>
<Link href="/blog">My blog</Link>
</nav>
</header>
      <main className={styles.main}>
<h1>Welcome to blogger boy</h1>
<p>This is a next JS blog application, features creating new posts, edit post, delete posts to a single anonymous user.</p>
      </main>
      <footer>
        <p>Created by Harsha HD</p>
      </footer>
    </>
  )
}
